Blood_Bank/Controllers/DonorController.cs
using Blood_Bank.Data;
using Blood_Bank.Models;
using Blood_Bank.HashPass;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace Blood_Bank.Controllers
{
    public class DonorController: Controller
    {
        ProjectDbContext _context;
        public DonorController(ProjectDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? id)
        {
            //chặn bằng ss
            if (HttpContext.Session.GetInt32("role") == null || HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Donor", "home");
            }

            User? user = await _context.User!.FirstOrDefaultAsync(x => x.Id == id!);
            ViewBag.Id = id;
            if (user == null)
            {
                return NotFound();
            }
            User dto = new User
            {
                Id = user.Id,
                Name = user.Name,
                Address = user.Address,
                Gender = user.Gender,
                City = user.City,
                Weight = user.Weight,
                BloodGroup = user.BloodGroup,
                Dob = user.Dob,
                ContactNumber = user.ContactNumber,
                Email = user.Email,
            };

            return View(dto);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            //chặn bằng ss
            if (HttpContext.Session.GetInt32("role") == null || HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Donor", "home");
            }

            User? user = await _context.User!.FirstOrDefaultAsync(x => x.Id == id!);
            ViewBag.Id = id;
            if (user == null)
            {
                return NotFound();
            }
            User dto = new User
            {
                Id = user.Id,
                Name = user.Name,
                Address = user.Address,
                Gender = user.Gender,
                City = user.City,
                Weight = user.Weight,
                BloodGroup = user.BloodGroup,
                Dob = user.Dob,
                ContactNumber = user.ContactNumber,
                Email = user.Email,
            };

            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id, User? user)
        {
            if (HttpContext.Session.GetInt32("role") == null || HttpContext.Session.GetInt32("role") == 1)
            {
                return RedirectToAction("Donor", "home");
            }

            //Validate

            User? old = await _context.User!.FirstOrDefaultAsync(x => x.Id == id!);

            if (old!.Name.Equals(user.Name) && old!.Address.Equals(user.Address) && old!.Gender == user.Gender && old!.City.Equals(user.City) && old!.Weight == user.Weight && old!.BloodGroup.Equals(user.BloodGroup) && old!.ContactNumber.Equals(user.ContactNumber) && old!.Dob == user.Dob && old!.Email.Equals(user.Email))
            {
                TempData["message"] = "Do not have any change!";
                return RedirectToAction("Edit", new { id = id });
            }

            var email = await _context.User!.SingleOrDefaultAsync(u => u.Email.Equals(user.Email) && u.Id != id);
            if (email != null)
            {
                TempData["message"] = "Email already exists!";
                return RedirectToAction("Edit", new { id = id });
            }
            var tel = await _context.User!.SingleOrDefaultAsync(u => u.ContactNumber.Equals(user.ContactNumber) && u.Id != id);
            if (tel != null)
            {
                TempData["message"] = "Contact number already exists!";
                return RedirectToAction("Edit", new { id = id });
            }
            var username = await _context.User!.SingleOrDefaultAsync(u => u.Username.Equals(user.Username) && u.Id != id);
            if (username != null)
            {
                TempData["message"] = "Username already exists!";
                return RedirectToAction("Edit", new { id = id });
            }

                //Update info
            
                old!.Name = user.Name;
                old!.Address = user.Address;
                old!.Gender = user.Gender;
                old!.City = user.City;
                old!.Weight = user.Weight;
                old!.BloodGroup = user.BloodGroup;
                old!.Dob = user.Dob;
                old!.ContactNumber = user.ContactNumber;
                old!.Email = user.Email;

                _context.User!.Update(old);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", new { id = id });
            
        }
        
        public async Task<IActionResult> ChangePassword()
        {
            //chặn bằng ss
            if (HttpContext.Session.GetInt32("role") == null || HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Donor", "home");
            }

            ViewBag.Id = HttpContext.Session.GetInt32("id");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(string? old, string confirm, string newP)
        {
            //chặn bằng ss
            if (HttpContext.Session.GetInt32("role") == null || HttpContext.Session.GetInt32("role") != 1)
            {
                return RedirectToAction("Donor", "home");
            }

            //Lấy id
            var id = HttpContext.Session.GetInt32("id");

            //Validate
            var user = await _context.User!.SingleOrDefaultAsync(m => m.Id == id);

            if(user.Password != MD5.md5(old))
            {
                TempData["message"] = "Old password not true!";
                ViewBag.Id = HttpContext.Session.GetInt32("id");
                return View();
            }

            if (newP == old)
            {
                TempData["message"] = "The new password is the same as the old password!";
                ViewBag.Id = HttpContext.Session.GetInt32("id");
                return View();
            }

            if (newP != confirm)
            {
                TempData["message"] = "The new password is not the same as the confirmation password!";
                ViewBag.Id = HttpContext.Session.GetInt32("id");
                return View();
            }

            //Update password
            User? oldPass = await _context.User!.FirstOrDefaultAsync(x => x.Id == id!);

            oldPass!.Password = MD5.md5(newP);

            _context.User!.Update(oldPass);
            await _context.SaveChangesAsync();

            TempData["message2"] = "Change password successful!";
            ViewBag.Id = HttpContext.Session.GetInt32("id");
            return View();
        }

        public async Task<IActionResult> DeleteAccount(int? id)
        {
            //chặn bằng ss
            if (HttpContext.Session.GetInt32("role") == null || HttpContext.Session.GetInt32("role") == 1)
            {
                return RedirectToAction("Donor", "home");
            }
            User? user = await _context.User!.FirstOrDefaultAsync(x => x.Id == id);
            _context.User!.Remove(user);
            await _context.SaveChangesAsync();
            
            UserRoles? role = await _context.UserRoles!.FirstOrDefaultAsync(x => x.UserId == id);
            _context.UserRoles!.Remove(role);
            await _context.SaveChangesAsync();

            HttpContext.Session.Clear();

            return RedirectToAction("Donor", "Home");
        }

    }
}

Blood_Bank/Controllers/LoginCheckController.cs
using Blood_Bank.Data;
using Blood_Bank.HashPass;
using Blood_Bank.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Principal;

namespace Blood_Bank.Controllers
{
    public class LoginCheckController : Controller
    {
        ProjectDbContext _context;
        public LoginCheckController(ProjectDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            //chặn bằng ss
            if (HttpContext.Session.GetInt32("role") != null)
            {
                return RedirectToAction("Donor", "home");
            }

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string username , string password)
        {

            if (ModelState.IsValid)
            {
                var user = await _context.User!.SingleOrDefaultAsync(m => m.Username == username && m.Password == MD5.md5(password));
                var accounts = await _context.User!.Where(m => m.Username == username).ToListAsync();

                if (accounts.Count() == 0)
                {
                    TempData["message"] = "Account no exist!";
                    return RedirectToAction("Index");
                }
                if (accounts.Count() != 0)
                {
                    if (accounts.First().Password == MD5.md5(password))
                    {
                        var session = HttpContext.Session;
                        session.SetInt32("id", user.Id);
                        session.SetString("name", user.Name);
                        session.SetString("city", user.City);
                        session.SetString("email", user.Email);
                        session.SetInt32("weight", (int)user.Weight);
                        session.SetString("address", user.Address);
                        session.SetString("phone", user.ContactNumber);
                        session.SetInt32("bloodgroup", (int)user.BloodGroup);
                        session.SetInt32("gender", (int)user.Gender);
                        session.SetString("name", user.Password);

                        ViewBag.Name = session.GetString("name");

                        if (session.Keys.Contains("username"))
                        {
                            return RedirectToAction("Login");
                        }
                        TempData["message2"] = "Login successful!";
                        return RedirectToAction("Donor", "home");
                    }
                }

                //if (user != null)
                //{
                //    HttpContext.Session.SetString("name", user.Name);
                //    HttpContext.Session.SetString("city", user.City);
                //    HttpContext.Session.SetString("email", user.Email);
                //    HttpContext.Session.SetInt32("weight", (int)user.Weight);
                //    HttpContext.Session.SetString("address", user.Address);
                //    HttpContext.Session.SetString("phone", user.ContactNumber);
                //    HttpContext.Session.SetInt32("bloodgroup", (int)user.BloodGroup);
                //    HttpContext.Session.SetInt32("gender", (int)user.Gender);
                //    HttpContext.Session.SetString("name", user.Password);
                //    return RedirectToAction("Index", "Home");
                //}
               
            }
            TempData["message"] = "Password Fail!";
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Donor", "home");
        }

    }
}

Blood_Bank/Controllers/RegistrationController.cs
using Blood_Bank.Data;
using Blood_Bank.HashPass;
using Blood_Bank.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.EntityFrameworkCore;

namespace Blood_Bank.Controllers
{
    public class RegistrationController : Controller
    {
        ProjectDbContext _context;
        public RegistrationController(ProjectDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(User data, UserRoles role)
        {
            var email = await _context.User!.SingleOrDefaultAsync(u => u.Email.Equals(data.Email));
            if(email != null)
            {
                TempData["message"] = "Email already exists!";
                return RedirectToAction("Index");
            }
            var tel = await _context.User!.SingleOrDefaultAsync(u => u.ContactNumber.Equals(data.ContactNumber));
            if (tel != null)
            {
                TempData["message"] = "Contact number already exists!";
                return RedirectToAction("Index");
            }
            var username = await _context.User!.SingleOrDefaultAsync(u => u.Username.Equals(data.Username));
            if (username != null)
            {
                TempData["message"] = "Username already exists!";
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                data.Password = MD5.md5(data.Password);
                _context.User!.Add(data);
                await _context.SaveChangesAsync();

                role.UserId = data.Id;
                role.RoleId = 1;
                _context.UserRoles!.Add(role);
                await _context.SaveChangesAsync();

                TempData["message2"] = "Registration successful!";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Blood_Bank/Controllers/SeekersController.cs
using Blood_Bank.Data;
using Blood_Bank.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blood_Bank.Controllers
{
    public class SeekersController : Controller
    {
        public ProjectDbContext _context;
        
        public SeekersController(ProjectDbContext context) {
            _context = context;
        }

        public ActionResult LifeSaving()
        {
            //LinQ
            var listLifeSaving = from ls in _context.User
                                 join lsRole in _context.UserRoles! on ls.Id equals lsRole.UserId
                                 where lsRole.RoleId == 3
                                 select new
                                 {
                                     Name = ls.Name,
                                     City = ls.City,
                                     ContactNumber = ls.ContactNumber,
                                     Email = ls.Email,
                                 };
            ViewBag.ListLifeSaving = listLifeSaving;
            return View();
        }

        public ActionResult SearchDonor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SearchDonor(string city, int bloodGroup)
        {
            var listDonor = from ld in _context.User
                            where ld.City == city
                            where ld.BloodGroup == bloodGroup
                            join ldRole in _context.UserRoles! on ld.Id equals ldRole.UserId
                            where ldRole.RoleId == 1
                            select new
                            {
                                Id = ld.Id,
                                Name = ld.Name,
                                City = ld.City,
                                BloodGroup = ld.BloodGroup,
                            };
            ViewBag.list = listDonor;
            var count = listDonor.Count();
            if(count == 0)
            {
                TempData["message"] = "SORRY DONORS ARE NOT AVAILABE WITH THE FOLLOWING BLOOD GROUP AND AREA";
                ViewBag.mess = TempData["message"];
            }
            return View(TempData["message"]);
        }

        public async Task<IActionResult> DonorDetail(int? id)
        {

            User? user = await _context.User!.FirstOrDefaultAsync(x => x.Id == id!);
            ViewBag.Id = id;
            if (user == null)
            {
                return NotFound();
            }
            User dto = new User
            {
                Id = user.Id,
                Name = user.Name,
                Address = user.Address,
                Gender = user.Gender,
                City = user.City,
                Weight = user.Weight,
                BloodGroup = user.BloodGroup,
                Dob = user.Dob,
                ContactNumber = user.ContactNumber,
                Email = user.Email,
            };

            return View(dto);
        }

        public ActionResult Mobilink()
        {
            return View();
        }
    }
}

Blood_Bank/Views/Home/Donor.cshtml
@{
    ViewData["Title"] = "Donor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["message2"] != null)
{
    <script>alert('@TempData["message2"]');</script>
}

<!-- ======= Services Section ======= -->
<section id="services" class="services services">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Blood Donor</h2>
        </div>

        <div class="row">
            @if (ViewBag.Role == 0)
            {
            <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="100">
                <div class="icon"><i class="fas fa-hospital-user"></i></div>
                <h4 class="title"><a asp-action="Index" asp-controller="Registration">Registration</a></h4>
                <p class="description">Those interested in donating blood can register here.</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="200">
                <div class="icon"><i class="fas fa-user-check"></i></div>
                <h4 class="title"><a asp-action="Index" asp-controller="LoginCheck">Login Check</a></h4>
                <p class="description">If you already have an account. Click here to proceed to the login page.</p>
            </div>
            }

            <!-- Sau khi đăng nhập thành công dùng cái này -->
            @if (ViewBag.Role == 1)
            {
             <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="100">
              <div class="icon"><i class="fas fa-user"></i></div>
              <h4 class="title"><a asp-action="Index" asp-controller="Donor" asp-route-id="@ViewBag.Id">Profile</a></h4>
              <p class="description">Details Modification</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="200">
              <div class="icon"><i class="far fa-caret-square-right"></i></div>
              <h4 class="title"><a asp-action="logout" asp-controller="LoginCheck">Logout</a></h4>
              <p class="description">If you want to leave then stay here.</p>
            </div> 
            }
            @if (ViewBag.Role == 3)
            {
                <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="100">
                    <div class="icon"><i class="fas fa-user"></i></div>
                    <h4 class="title"><a asp-action="Index" asp-controller="LifeSaving" asp-route-id="@ViewBag.Id">Life Saving Profile</a></h4>
                    <p class="description">Details Modification</p>
                </div>
                <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="200">
                    <div class="icon"><i class="far fa-caret-square-right"></i></div>
                    <h4 class="title"><a asp-action="logout" asp-controller="LoginCheck">Logout</a></h4>
                    <p class="description">If you want to leave then stay here.</p>
                </div>
            }
        </div>

    </div>
</section><!-- End Services Section -->

Blood_Bank/Views/Home/Seeker.cshtml
@{
    ViewData["Title"] = "Seeker";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ======= Services Section ======= -->
<section id="services" class="services services">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Blood Seeker</h2>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="100">
                <div class="icon"><i class="fa fa-phone-square"></i></div>
                <h4 class="title"><a asp-action="LifeSaving" asp-controller="Seekers">Life Saving Contact</a></h4>
                <p class="description">If you can't find the information you need, here are the details to contact our lifesavers.</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="200">
                <div class="icon"><i class="fa fa-search"></i></div>
                <h4 class="title"><a asp-action="SearchDonor" asp-controller="Seekers">Donor search</a></h4>
                <p class="description">Find the donor information you need.</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="zoom-in" data-aos-delay="200">
                <div class="icon"><i class="fa fa-volume-control-phone"></i></div>
                <h4 class="title"><a asp-action="Mobilink" asp-controller="Seekers">Mobilink Paging Services</a></h4>
                <p class="description">If you can't find the information you need and cannot contact lifeguards, this service may be able to help.</p>
            </div>

        </div>

    </div>
</section><!-- End Services Section -->

Blood_Bank/Views/Home/TermOfService.cshtml
@{
    ViewData["Title"] = "TermOfService";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="contact" class="contact">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>Term Of Service</h2>
        </div>

        <div class="container">
            <p>Last Edit: 01/01/2023</p>
            <p>
                Get tested
                All blood units collected will be tested for blood type (ABO-Rh), HIV, hepatitis B virus, hepatitis C virus, syphilis.
                When donating blood at Blood Bank, you will be informed of the results by the department,
                kept confidential and consulted (free of charge) when the above infections are detected.
            </p>
            <p>
                Get free health check and consultation
                Participants who donate blood are checked for indicators such as weight, blood pressure,
                heart rate and measured parameters as the basis of health assessment.
            </p>
            <p>
                Be trained and cared for according to current regulations
                Like other blood donation sites, when voluntary blood donation at Blood Bank,
                blood donors will be fostered and cared for according to regulations:
                Received a certificate of voluntary blood donation from the Provincial Steering Committee for Humanitarian Blood Donation.
                In addition to the honorary value, the blood donation certificate has the value of blood reimbursement.
                If you have ever participated in blood donation, during your life,
                if you unfortunately need blood, the State will guarantee to reimburse you for free for the exact amount of blood you have donated.
            </p>


        </div>
    </div>
</section><!-- End Appointment Section -->

Blood_Bank/Views/Home/faq.cshtml
@{
    ViewData["Title"] = "faq";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="faq" class="faq section-bg">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Frequently Asked Questioins</h2>
            <p></p>
        </div>

        <ul class="faq-list">

            <li>
                <div data-bs-toggle="collapse" class="collapsed question" href="#faq1">Information about blood and its importance. <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq1" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        Blood is a cellular organelle made up of the tangible components of cells (red blood cells, white blood cells, platelets) and plasma. The main role of the blood is to provide nutrients and structure to the organs as well as to remove waste products in the body's metabolism such as carbon dioxide and lactic acid.
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq2" class="collapsed question">How and why they should donate blood? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq2" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        Donating blood increases calorie burning and aids in weight loss. It is estimated that each donation of 450 ml of blood helps to burn about 650 calories in the body and reduce blood cholesterol. This is a useful measure in weight loss in people with an above-average body weight.
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq3" class="collapsed question">What are the conditions for blood donation? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq3" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        Healthy people, completely voluntary blood donation. <br>
                        Age: 18-60 years old. <br>
                        Weight: ≥ 42 kg for women and ≥ 45 kg for men. The amount of blood donated each time should not exceed 9ml/kg of body weight. <br><br>
                        Hemoglobin: 120 g/l
                        Not infected or not infected with HIV and other blood-borne diseases (hepatitis B virus, hepatitis C virus, syphilis...). <br>
                        Last donated blood 12 weeks ago or last donated blood components 3 weeks ago. <br>
                        Women who are not pregnant or do not raise children under 1 year old. <br>
                        Bring one of the identification documents: ID card, citizen identification card, passport, driver's license ... <br>
                        Healthy people donate no more than 9 ml/kg body weight each time. People weighing 45 - 50 kg can donate 350 ml of whole blood, people from 50 kg or more can donate 450 ml of whole blood. <br>
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq4" class="collapsed question">Are their any side effects of Blood donations ? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq4" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        There are no side effects of blood donation. The Blood bank staff ensures that your blood donation is a good experience as far as possible to enable you to become a repeat and a regular blood donor. There are a number of people who have donated   more tha25-100 times in their life time.
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq5" class="collapsed question">Can I get any disease like AIDS or Hepatitis or any other disease by Blood donation ? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq5" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        As only sterile disposables are used to collect  blood and these disposables can be used only one time it eliminates any chances of acquiring any disease from blood donation.
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq6" class="collapsed question">How often can I donate Blood ? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq6" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        After every three –four months you can donate blood.
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq8" class="collapsed question">What happens to blood I donate ? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq8" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        Your blood in the blood bank is processed and within 6 hours of Blood collection It  is separated into components viz. Red Cells, White Cells, Plasma & Platelets. These Blood components are made available for the patients. By making blood components, all the useful parts of blood can be used and from one unit of blood four patients can be benefited. <br> <br>

                        Post Donation care -Care that a donor should take after donating blood.  <br> <br>

                        1. Eat and Drink  the refreshment provided before leaving the blood bank <br>
                        2. Drink more liquids than usual in next 4 hours <br>
                        3. Avoid consuming alcohol until you have eaten something <br>
                        4. Don't smoke for next 30 minutes <br>
                        5. Avoid climbing stairs for next 30 minutes <br>
                        6. If there is bleeding from the phlebotomy site, raise the arm and apply pressure <br>
                        7. If fainting or dizziness occurs, either lie down or sit with the head between the knees <br>
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq7" class="collapsed question">What should I eat before blood-donation ? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq7" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        You will be asked to fill a donor form. Your medical history will be taken by a medical personnel and  a small drop of blood to check blood group as well as  Hb for anemia. After  simple medical screening process and being found medically fit to donate, you will be sent to blood collection  room. The actual blood collection from the donor takes about 7-10 minutes followed by a little rest and refreshments.
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq9" class="collapsed question">How much  time does it take to donate blood ? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq9" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        After every three –four months you can donate blood.
                    </p>
                </div>
            </li>

        </ul>

    </div>
</section><!-- End Frequently Asked Questioins Section -->