Blood_Bank/Controllers/MailController.cs
using Blood_Bank.Data;
using Blood_Bank.Models;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blood_Bank.Controllers
{
    public class MailController : Controller
    {
        ProjectDbContext _context;
        private readonly IEmailSender _emailSender;
        public MailController(IEmailSender emailSender, ProjectDbContext context)
        {
            _emailSender = emailSender;
            _context = context;
        }


        [HttpPost]
        public async Task<IActionResult> SendMail(string email, string subject, string htmlMessage)
        {
            await _emailSender.SendEmailAsync(email, subject, htmlMessage);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> SendMailContact(string email, string subject, string htmlMessage)
        {
            email = "vinhxin1105@gmail.com";
            await _emailSender.SendEmailAsync(email, subject, htmlMessage);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> SendMailHtml(string email, string subject)
        {
            //Fetching Email Body Text from EmailTemplate File.  
            string FilePath = "wwwroot/mail/test.html";
            StreamReader str = new StreamReader(FilePath);
            string htmlMessage = str.ReadToEnd();
            str.Close();

            //Repalce [newusername] = signup user name   
            //MailText = MailText.Replace("[newusername]", txtUserName.Text.Trim());

            await _emailSender.SendEmailAsync(email, subject, htmlMessage);
            return RedirectToAction("Index", "Home");

        }

        [HttpPost]
        public async Task<IActionResult> SendMailHtmls(string mail, string phone, string message)
        {
            List<string> list = (from ld in _context.User
                                 join ldRole in _context.UserRoles! on ld.Id equals ldRole.UserId
                                 where ldRole.RoleId == 1
                                 select ld.Email).Distinct().ToList();
            //var list = IQueryabl.Select(s => new { Email = s.Email }).AsEnumerable().Cast<dynamic>().ToList<dynamic>(); ;
            string[] arr = list.ToArray();
            string email = string.Join(",", arr);
            string subject = "Blood Bank";
            //Fetching Email Body Text from EmailTemplate File.  
            string FilePath = "wwwroot/mail/SendMail.html";
            StreamReader str = new StreamReader(FilePath);
            string htmlMessage = str.ReadToEnd();
            str.Close();
             
            //Repalce [mail] = name email  
            htmlMessage = htmlMessage.Replace("[mail]", mail.ToString().Trim());
            htmlMessage = htmlMessage.Replace("[phone]", phone.ToString().Trim());
            htmlMessage = htmlMessage.Replace("[message]", message.ToString().Trim());

            await _emailSender.SendEmailAsync(email, subject, htmlMessage);
            TempData["message"] = "Send email successful!";

            return RedirectToAction("Mobilink", "Seekers");

        }
    }
}

Blood_Bank/Controllers/SeekersController.cs
using Blood_Bank.Data;
using Blood_Bank.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blood_Bank.Controllers
{
    public class SeekersController : Controller
    {
        public ProjectDbContext _context;
        
        public SeekersController(ProjectDbContext context) {
            _context = context;
        }

        public ActionResult LifeSaving()
        {
            //LinQ
            var listLifeSaving = from ls in _context.User
                                 join lsRole in _context.UserRoles! on ls.Id equals lsRole.UserId
                                 where lsRole.RoleId == 3
                                 select new
                                 {
                                     Name = ls.Name,
                                     City = ls.City,
                                     ContactNumber = ls.ContactNumber,
                                     Email = ls.Email,
                                 };
            ViewBag.ListLifeSaving = listLifeSaving;
            return View();
        }

        public ActionResult SearchDonor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SearchDonor(string city, int bloodGroup)
        {
            var listDonor = from ld in _context.User
                            where ld.City == city
                            where ld.BloodGroup == bloodGroup
                            join ldRole in _context.UserRoles! on ld.Id equals ldRole.UserId
                            where ldRole.RoleId == 1
                            select new
                            {
                                Id = ld.Id,
                                Name = ld.Name,
                                City = ld.City,
                                BloodGroup = ld.BloodGroup,
                            };
            ViewBag.list = listDonor;
            var count = listDonor.Count();
            if(count == 0)
            {
                TempData["message"] = "SORRY DONORS ARE NOT AVAILABE WITH THE FOLLOWING BLOOD GROUP AND AREA";
                ViewBag.mess = TempData["message"];
            }
            return View(TempData["message"]);
        }

        public async Task<IActionResult> DonorDetail(int? id)
        {

            User? user = await _context.User!.FirstOrDefaultAsync(x => x.Id == id!);
            ViewBag.Id = id;
            if (user == null)
            {
                return NotFound();
            }
            User dto = new User
            {
                Id = user.Id,
                Name = user.Name,
                Address = user.Address,
                Gender = user.Gender,
                City = user.City,
                Weight = user.Weight,
                BloodGroup = user.BloodGroup,
                Dob = user.Dob,
                ContactNumber = user.ContactNumber,
                Email = user.Email,
            };

            return View(dto);
        }

        public ActionResult Mobilink()
        {
            return View();
        }
    }
}

Blood_Bank/Views/Seekers/DonorDetail.cshtml
@model Blood_Bank.Models.User
@{
    ViewData["Title"] = "Donor Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ======= Appointment Section ======= -->
<section id="appointment" class="appointment section-bg">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Donor Detail</h2>
        </div>
        <form asp-action="" method="POST" data-aos="fade-up" data-aos-delay="100">
            <div class="row">
                <div class="col-md-4 form-group">
                    <input type="text" asp-for="Name" placeholder="Your Name" disabled>
                </div>
                <div class="col-md-4 form-group mt-3 mt-md-0">
                    <input type="email" asp-for="Email" placeholder="Your Email" disabled>
                </div>
                <div class="col-md-4 form-group mt-3 mt-md-0">
                    <input type="number" asp-for="Weight" placeholder="Your Weight" disabled>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 form-group mt-3">
                    <input type="date" class=" datepicker" asp-for="Dob" placeholder="Date Of Birth" disabled>
                </div>
                <div class="col-md-4 form-group mt-3">
                    <input type="tel" class="" asp-for="ContactNumber" placeholder="Your Phone" disabled>
                </div>
                <div class="col-md-4 form-group mt-3">
                    <select asp-for="BloodGroup" class="sele" disabled>
                        <option value="" disabled selected>Blood group</option>
                        <option value="1">Group A</option>
                        <option value="2">Group B</option>
                        <option value="3">Group AB</option>
                        <option value="4">Group O</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 form-group mt-3">
                    <input type="text" class=" datepicker" asp-for="Address" placeholder="Your Address" disabled>
                </div>
                <div class="col-md-4 form-group mt-3">
                    <input type="text" asp-for="City" disabled />
                </div>
                <div class="col-md-4 mt-3 form-group">
                    <select asp-for="Gender" class="sele" disabled>
                        <option value="" disabled selected>Gender</option>
                        <option value="1">Male</option>
                        <option value="2">Fmale</option>
                    </select>
                </div>
            </div>
            <div class="col-md-12 form-group mt-3">
                <br />
            </div>
            <div class="text-center">
                <a class="loginC" asp-action="SearchDonor" asp-controller="Seekers">Back</a>
            </div>
        </form>

    </div>
</section><!-- End Appointment Section -->

<style>
    .loginC {
        background: #C6414C;
        border: 0;
        padding: 10px 35px;
        color: #fff;
        transition: 0.4s;
        border-radius: 50px;
    }

        .loginC:hover {
            color: #fff;
            background: #B30513;
        }

    input {
        width: 100%;
        border: 1px solid;
        border-color: #CED4DA;
        box-shadow: none;
        font-size: 14px;
        padding: 10px 15px;
        outline: none;
        border-radius: 20px;
    }

        input:focus {
            border-color: #C6414C;
        }

    .sele {
        width: 100%;
        border: 1px solid;
        border-color: #CED4DA;
        box-shadow: none;
        font-size: 14px;
        padding: 10px 15px;
        outline: none;
        border-radius: 100px;
    }

        .sele:focus {
            border-color: #C6414C;
        }

    .regis {
        background: #C6414C;
        border: 0;
        padding: 10px 35px;
        color: #fff;
        transition: 0.4s;
        border-radius: 50px;
    }

        .regis:hover {
            background: #B30513;
        }
</style>

Blood_Bank/Views/Seekers/LifeSaving.cshtml
@{
    ViewData["Title"] = "LifeSaving";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="lifeSaving" class="lifeSaving">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>Life Saving Contact</h2>
        </div>

        <div class="container">
            <!-- Start Row -->

            <div class="row">
                
                @foreach (var item in ViewBag.ListLifeSaving)
                {
                    <!-- Start Col -->
                    <div class="col-sm-12 col-lg-6 mb-4">
                        <!-- Start Card -->
                        <div class="card mb-3 shadow-lg border border-1 border-light" style="max-width: 550px;">
                            <div class="row g-0">
                                <div class="col-md-4 col-sm-12 border border-4 rounded-start border-opacity-90 border-end-0 border-danger">
                                    <img src="~/assets/img/LifeSaving/1.jfif" class="img-fluid rounded-start" style="height: 270px;" alt="...">
                                </div>
                                <div class="col-md-8 col-sm-12 ">
                                    <div class="card-body mt-2">
                                        <i class="fas fa-map-marker-alt"></i> <small>@item.City</small>
                                        <h5 class="card-title text-secondary"> @item.Name </h5>
                                        <br>
                                        <h6 class="text-primary">Contact Infomation</h6>
                                        <i class="fas fa-phone"></i> <small>Number : </small> <span class="lead">@item.ContactNumber</span> <br>
                                        <i class="fas fa-envelope"></i> <small>Email : </small> <span class="lead">@item.Email</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- End Card -->
                    </div>
                    <!-- End Col -->
                }

            </div>
            <!-- End Row-->
        </div>
    </div>
</section><!-- End Appointment Section -->

Blood_Bank/Views/Seekers/Mobilink.cshtml
@{
    ViewData["Title"] = "Mobilink";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ======= Appointment Section ======= -->
<section id="appointment" class="appointment section-bg">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Mobilink Paging Service</h2>
            <p>
                Mobilink messaging service to send messages to all donors in the area requesting blood of a specific group. Donors who see the message and have the same blood type can then contact the individual needing blood to offer assistance.
            </p>
        </div>
        @if (TempData["message"] != null)
        {
            @*<script>alert('@TempData["message"]');</script>*@
            <div style="text-align: center;">
                <span style="color: limegreen">@TempData["message"]</span><br><br>
            </div>
        }
        <form asp-action="SendMailHtmls" asp-controller="Mail" method="post" role="form" class="php-email-form">
            <div class="row">
            <div class="col-md-6 form-group mt-6">
                <input type="email" name="mail" id="name" placeholder="Your email" required="">
            </div>
            <div class="col-md-6 form-group mt-6">
                <input type="tel" name="phone" id="email" placeholder="Your phone" required="">
            </div>
            <div class="my-2"></div>
            <div class="form-group mt-12">
                <textarea name="message" rows="7" placeholder="Message" required=""></textarea>
            </div>
            <div class="my-2">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">You have successfully sent the message</div>
            </div>
            <div class="text-center"><button class="loginC" type="submit">Send Message</button></div>
            </div>
        </form>

        @*<script>
            function loading(){
                thisForm.querySelector('.loading').classList.add('d-block');
                setTimeout(function(){
                    $("form").submit();
                }, 1);
                return true;
            }
            
        </script>*@

        <style>
            .loginC {
                background: #C6414C;
                border: 0;
                padding: 10px 35px;
                color: #fff;
                transition: 0.4s;
                border-radius: 12px;
            }

                .loginC:hover {
                    background: #B30513;
                }

            input {
                width: 100%;
                border: 1px solid;
                border-color: #CED4DA;
                box-shadow: none;
                font-size: 14px;
                padding: 10px 15px;
                outline: none;
                border-radius: 12px;
            }

                input:focus {
                    border-color: #C6414C;
                }

            textarea {
                width: 100%;
                border: 1px solid;
                border-color: #CED4DA;
                box-shadow: none;
                font-size: 14px;
                padding: 10px 15px;
                outline: none;
                border-radius: 12px;
            }

                textarea:focus {
                    border-color: #C6414C;
                }
        </style>

    </div>
</section><!-- End Appointment Section -->

Blood_Bank/Views/Seekers/SearchDonor.cshtml
@{
    ViewData["Title"] = "SearchDonor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="counts" class="counts">
    <div class="container count-box" data-aos="fade-up">

        <div class="section-title">
            <h2>Search Donor</h2>
        </div>

        @if(ViewBag.mess != null){
            @*<script>alert('@TempData["message"]');</script>*@
            <div style="text-align: center;">
                <span style="color: red; font-size: smaller">@ViewBag.mess</span><br><br>
            </div>
        }

        <form asp-action="SearchDonor" method="POST" role="form" data-aos="fade-up" data-aos-delay="100">
            <div class="row">
              
                <div class="col-md-4 form-group mt-3">
                    <select name="city" id="city" class="searchSelect" required>
                        <option disabled selected value="">--Area--</option>
                        <option disabled value="">--Viet Nam--</option>
                        <!--- Viet Nam states -->
                            <option value="An Giang">An Giang</option>
                            <option value="Bà Rịa-Vũng Tàu">Bà Rịa-Vũng Tàu</option>
                            <option value="Bắc Giang">Bắc Giang</option>
                            <option value="Bắc Kạn">Bắc Kạn</option>
                            <option value="Bạc Liêu">Bạc Liêu</option>
                            <option value="Bắc Ninh">Bắc Ninh</option>
                            <option value="Bến Tre">Bến Tre</option>
                            <option value="Bình Dương">Bình Dương</option>
                            <option value="Bình Định">Bình Định</option>
                            <option value="Bình Phước">Bình Phước</option>
                            <option value="Bình Thuận">Bình Thuận</option>
                            <option value="Cà Mau">Cà Mau</option>
                            <option value="Cao Bằng">Cao Bằng</option>
                            <option value="Đà Nẵng">Đà Nẵng</option>
                            <option value="Đắk Lắk">Đắk Lắk</option>
                            <option value="Đắk Nông">Đắk Nông</option>
                            <option value="Điện Biên">Điện Biên</option>
                            <option value="Đồng Nai">Đồng Nai</option>
                            <option value="Đồng Tháp">Đồng Tháp</option>
                            <option value="Gia Lai">Gia Lai</option>
                            <option value="Hà Giang">Hà Giang</option>
                            <option value="Hà Nam">Hà Nam</option>
                            <option value="Hà Tây">Hà Tây</option>
                            <option value="Hà Tĩnh">Hà Tĩnh</option>
                            <option value="Hải Dương">Hải Dương</option>
                            <option value="Hải Phòng">Hải Phòng</option>
                            <option value="Hà Nội">Hà Nội</option>
                            <option value="Hậu Giang">Hậu Giang</option>
                            <option value="Ho Chi Minh City">Ho Chi Minh City</option>
                            <option value="Hòa Bình">Hòa Bình</option>
                            <option value="Hưng Yên">Hưng Yên</option>
                            <option value="Khánh Hòa">Khánh Hòa</option>
                            <option value="Kiên Giang">Kiên Giang</option>
                            <option value="Kon Tum">Kon Tum</option>
                            <option value="Lai Châu">Lai Châu</option>
                            <option value="Lâm Đồng">Lâm Đồng</option>
                            <option value="Lạng Sơn">Lạng Sơn</option>
                            <option value="Lào Cai">Lào Cai</option>
                            <option value="Long An">Long An</option>
                            <option value="Nam Định">Nam Định</option>
                            <option value="Nghệ An">Nghệ An</option>
                            <option value="Ninh Bình">Ninh Bình</option>
                            <option value="Ninh Thuận">Ninh Thuận</option>
                            <option value="Phú Thọ">Phú Thọ</option>
                            <option value="Phú Yên">Phú Yên</option>
                            <option value="Quảng Bình">Quảng Bình</option>
                            <option value="Quảng Nam">Quảng Nam</option>
                            <option value="Quảng Ngãi">Quảng Ngãi</option>
                            <option value="Quảng Ninh">Quảng Ninh</option>
                            <option value="Quảng Trị">Quảng Trị</option>
                            <option value="Sóc Trăng">Sóc Trăng</option>
                            <option value="Sơn La">Sơn La</option>
                            <option value="Tây Ninh">Tây Ninh</option>
                            <option value="Thái Bình">Thái Bình</option>
                            <option value="Thái Nguyên">Thái Nguyên</option>
                            <option value="Thanh Hóa">Thanh Hóa</option>
                            <option value="Thừa Thiên-Huế">Thừa Thiên-Huế</option>
                            <option value="Tiền Giang">Tiền Giang</option>
                            <option value="Trà Vinh">Trà Vinh</option>
                            <option value="Tuyên Quang">Tuyên Quang</option>
                            <option value="Vĩnh Long">Vĩnh Long</option>
                            <option value="Vĩnh Phúc">Vĩnh Phúc</option>
                            <option value="Yên Bái">Yên Bái</option>

                            <!--- India states -->
                            <option disabled value="">--India--</option>
                            <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
                            <option value="Andhra Pradesh">Andhra Pradesh</option>
                            <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                            <option value="Assam">Assam</option>
                            <option value="Bihar">Bihar</option>
                            <option value="Chandigarh">Chandigarh</option>
                            <option value="Chhattisgarh">Chhattisgarh</option>
                            <option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
                            <option value="Daman and Diu">Daman and Diu</option>
                            <option value="Delhi">Delhi</option>
                            <option value="Goa">Goa</option>
                            <option value="Gujarat">Gujarat</option>
                            <option value="Haryana">Haryana</option>
                            <option value="Himachal Pradesh">Himachal Pradesh</option>
                            <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                            <option value="Jharkhand">Jharkhand</option>
                            <option value="Karnataka">Karnataka</option>
                            <option value="Kerala">Kerala</option>
                            <option value="Ladakh">Ladakh</option>
                            <option value="Lakshadweep">Lakshadweep</option>
                            <option value="Madhya Pradesh">Madhya Pradesh</option>
                            <option value="Maharashtra">Maharashtra</option>
                            <option value="Manipur">Manipur</option>
                            <option value="Meghalaya">Meghalaya</option>
                            <option value="Mizoram">Mizoram</option>
                            <option value="Nagaland">Nagaland</option>
                            <option value="Odisha">Odisha</option>
                            <option value="Puducherry">Puducherry</option>
                            <option value="Punjab">Punjab</option>
                            <option value="Rajasthan">Rajasthan</option>
                            <option value="Sikkim">Sikkim</option>
                            <option value="Tamil Nadu">Tamil Nadu</option>
                            <option value="Telangana">Telangana</option>
                            <option value="Tripura">Tripura</option>
                            <option value="Uttar Pradesh">Uttar Pradesh</option>
                            <option value="Uttarakhand">Uttarakhand</option>
                            <option value="West Bengal">West Bengal</option>
                    </select>
                </div>
                <div class="col-md-4 form-group mt-3">
                    <select name="bloodGroup" id="department" class="searchSelect" required>
                        <option disable select value="">Blood group</option>
                        <option value="1">Group A</option>
                        <option value="2">Group B</option>
                        <option value="3">Group AB</option>
                        <option value="4">Group O</option>
                    </select>
                </div>
                <div class="col-md-4 form-group mt-3">
                    <button class="searchButton" style="width: 100%" type="submit">Search</button>
                </div>
            </div>
        </form>
        <br><br>

        <div class="row">
            <table style="text-align:center" class="table">
                  <tr>
                        <th>Name</th>
                        <th>City</th>
                        <th>Blood Group</th>
                        <th>
                            Action
                        </th>
                    </tr>
                @if(ViewBag.list != null)
                {
                    @foreach (var item in ViewBag.list)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.City</td>
                            <td>
                                @if (item.BloodGroup == 1){
                                    var BloodG = "A";
                                    @BloodG
                                }
                                else if (item.BloodGroup == 2){
                                    var BloodG = "B";
                                    @BloodG
                                }
                                else if (item.BloodGroup == 3){
                                    var BloodG = "AB";
                                    @BloodG
                                } else {
                                    var BloodG = "O";
                                    @BloodG
                                }
                            </td>
                            <td>
                                <a asp-action="DonorDetail" asp-route-id="@item.Id">View detail</a>
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>

    </div>
</section><!-- End Services Section -->

<style>
    .view {
        border: none;
        background-color: #C6414C;
        color: #ffffff;
        border-radius: 7px;
        width: 100px;
    }

        .view:hover {
            background-color: #B30513;
        }

    .searchSelect {
        width: 100%;
        border: 1px solid;
        box-shadow: none;
        font-size: 14px;
        padding: 10px 15px;
        outline: none;
    }

        .searchSelect:focus {
            border-color: #C6414C;
        }

    .searchButton {
        background-color: #C6414C;
        width: 100%;
        border: none;
        box-shadow: none;
        font-size: 14px;
        padding: 10px 15px;
        color: #fff;
        outline: none;
    }

        .searchButton:hover {
            background-color: #B30513;
        }
</style>